In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# Create a variable
zero = tf.Variable(0)

In [3]:
# Create a constant
one = tf.constant(1)

In [4]:
new_value = tf.add(zero,one)

In [6]:
# Variable can be changed
update = tf.assign(zero,new_value)

In [7]:
# Create a session
sess = tf.Session()

In [8]:
init_op = tf.global_variables_initializer()

In [9]:
sess.run(init_op)

In [10]:
sess.run(update)

1

In [12]:
# for loop
for i in range(5):
    sess.run(update)
    print(sess.run(zero))

2
3
4
5
6


In [15]:
z = tf.Variable(0)
z1 = tf.assign(z,zero)

In [19]:
for _ in range(10):
    sess.run(z1)
    print(sess.run(z1))

6
6
6
6
6
6
6
6
6
6


In [20]:
for _ in range(10):
    sess.run(z)
    print(sess.run(z))

6
6
6
6
6
6
6
6
6
6


## String

In [21]:
hello = tf.constant("Hello")

In [22]:
world = tf.constant('World')

In [24]:
hw = tf.add(hello,world)

In [25]:
print(sess.run(hw))

b'HelloWorld'


In [26]:
fname = tf.constant('John')

In [27]:
lname = tf.constant("Lobo")

In [28]:
full_name = tf.add(fname,lname)

In [29]:
sess.run(full_name)

b'JohnLobo'

## Placeholder

In [30]:
a = tf.placeholder(tf.float32)

In [31]:
b = a * 3

In [32]:
# Feeding the a value
result = sess.run(b,feed_dict={a:2})

In [33]:
print(result)

6.0


In [34]:
result = sess.run(b,feed_dict={a:[3,4,5]})

In [35]:
print(result)

[ 9. 12. 15.]


In [36]:
# Placeholder as a single
result = sess.run(b,feed_dict={a:5})
print(result)

15.0


In [37]:
# Placeholder as 2d 
result = sess.run(b,feed_dict={a:[3,6,9]})
print(result)

[ 9. 18. 27.]


In [38]:
# Place holder as multidimensinal
dict1 = {a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

result = sess.run(b,feed_dict=dict1)
print(result)

[[[ 3.  6.  9.]
  [12. 15. 18.]
  [21. 24. 27.]
  [30. 33. 36.]]

 [[39. 42. 45.]
  [48. 51. 54.]
  [57. 60. 63.]
  [66. 69. 72.]]]


In [39]:
result.shape

(2, 4, 3)

In [40]:
sess.close()

In [41]:
# another type of code to run session

In [43]:
with tf.Session() as sess:
    new = sess.run(full_name)
    print(new)

b'JohnLobo'
